services:
  tarantool:
    build: .
    image: tdb-tarantool
    command: tarantool /app/backend/init.lua
    volumes:
      - ./backend:/app/backend:ro
      - ./frontend:/app/frontend:ro
      - ./schema:/app/schema:ro
      - ./tests:/app/tests:ro
      - tgui_data:/var/lib/tarantool
    ports:
      - "3301:3301"   # Tarantool binary port
      - "8080:8080"   # HTTP GUI port
    environment:
      TT_LOG_LEVEL: "5"

volumes:
  tgui_data:
