[po4a_langs] fr
[po4a_paths] po/tdb-docs.pot $lang:po/$lang.po

[type: text] doc/en/README.md $lang:doc/$lang/README.md
[type: text] doc/en/get-started.md $lang:doc/$lang/get-started.md
[type: text] doc/en/reference.md $lang:doc/$lang/reference.md
[type: text] doc/en/api.md $lang:doc/$lang/api.md
[type: text] doc/en/dev.md $lang:doc/$lang/dev.md
[type: text] doc/en/dev/architecture.md $lang:doc/$lang/dev/architecture.md
[type: text] doc/en/dev/runtime.md $lang:doc/$lang/dev/runtime.md
[type: text] doc/en/dev/graphql.md $lang:doc/$lang/dev/graphql.md
[type: text] doc/en/dev/frontend.md $lang:doc/$lang/dev/frontend.md
[type: text] doc/en/dev/tests.md $lang:doc/$lang/dev/tests.md
