local R = require('tests.runner')
print("══════════════════════════════════════")
print("   tdb — suite de tests")
print("══════════════════════════════════════")
require('tests.test_lexer')
require('tests.test_parser')
require('tests.test_schema')
require('tests.test_executor')
math.randomseed(os.time())
require('tests.test_spaces')
require('tests.test_triggers')
return R.summary()
