local R = require('tests.runner')
local parse
parse = require('graphql.parser').parse
local first_def
first_def = function(src)
  return parse(src).definitions[1]
end
local first_field
first_field = function(src)
  return first_def(src).selectionSet.selections[1]
end
R.describe("Parser — document", function()
  R.it("produit un nœud Document", function()
    local doc = parse("{ hello }")
    R.eq(doc.kind, 'Document')
    return R.ok(doc.definitions)
  end)
  R.it("une définition pour une opération anonyme", function()
    local doc = parse("{ hello }")
    return R.eq(#doc.definitions, 1)
  end)
  return R.it("plusieurs définitions", function()
    local doc = parse("query A { a } query B { b }")
    return R.eq(#doc.definitions, 2)
  end)
end)
R.describe("Parser — opérations", function()
  R.it("sélection courte → query anonyme", function()
    local def = first_def("{ hello }")
    R.eq(def.kind, 'OperationDefinition')
    R.eq(def.operation, 'query')
    return R.is_nil(def.name)
  end)
  R.it("mot-clé query explicite", function()
    local def = first_def("query { hello }")
    return R.eq(def.operation, 'query')
  end)
  R.it("query nommé", function()
    local def = first_def("query MonQuery { hello }")
    return R.eq(def.name, 'MonQuery')
  end)
  R.it("mutation", function()
    local def = first_def("mutation { doSomething }")
    return R.eq(def.operation, 'mutation')
  end)
  return R.it("mutation nommée", function()
    local def = first_def("mutation DoIt { doSomething }")
    return R.eq(def.name, 'DoIt')
  end)
end)
R.describe("Parser — SelectionSet et Fields", function()
  R.it("champ simple", function()
    local f = first_field("{ hello }")
    R.eq(f.kind, 'Field')
    return R.eq(f.name, 'hello')
  end)
  R.it("plusieurs champs", function()
    local def = first_def("{ a b c }")
    return R.eq(#def.selectionSet.selections, 3)
  end)
  R.it("champ avec alias", function()
    local f = first_field("{ myAlias: hello }")
    R.eq(f.alias, 'myAlias')
    return R.eq(f.name, 'hello')
  end)
  R.it("SelectionSet imbriqué", function()
    local f = first_field("{ outer { inner } }")
    R.eq(f.name, 'outer')
    R.ok(f.selectionSet)
    return R.eq(f.selectionSet.selections[1].name, 'inner')
  end)
  return R.it("imbrication profonde", function()
    local f = first_field("{ a { b { c } } }")
    local inner = f.selectionSet.selections[1].selectionSet.selections[1]
    return R.eq(inner.name, 'c')
  end)
end)
R.describe("Parser — arguments", function()
  R.it("argument entier", function()
    local f = first_field("{ f(x: 42) }")
    R.eq(#f.arguments, 1)
    R.eq(f.arguments[1].name, 'x')
    R.eq(f.arguments[1].value.kind, 'IntValue')
    return R.eq(f.arguments[1].value.value, '42')
  end)
  R.it("argument chaîne", function()
    local f = first_field('{ f(s: "hello") }')
    local arg = f.arguments[1]
    R.eq(arg.value.kind, 'StringValue')
    return R.eq(arg.value.value, 'hello')
  end)
  R.it("argument flottant", function()
    local f = first_field("{ f(n: 3.14) }")
    return R.eq(f.arguments[1].value.kind, 'FloatValue')
  end)
  R.it("argument booléen true", function()
    local f = first_field("{ f(b: true) }")
    R.eq(f.arguments[1].value.kind, 'BooleanValue')
    return R.eq(f.arguments[1].value.value, true)
  end)
  R.it("argument booléen false", function()
    local f = first_field("{ f(b: false) }")
    return R.eq(f.arguments[1].value.value, false)
  end)
  R.it("argument null", function()
    local f = first_field("{ f(x: null) }")
    return R.eq(f.arguments[1].value.kind, 'NullValue')
  end)
  R.it("argument liste", function()
    local f = first_field("{ f(l: [1, 2, 3]) }")
    R.eq(f.arguments[1].value.kind, 'ListValue')
    return R.eq(#f.arguments[1].value.values, 3)
  end)
  R.it("argument objet", function()
    local f = first_field('{ f(o: {a: 1, b: "x"}) }')
    R.eq(f.arguments[1].value.kind, 'ObjectValue')
    return R.eq(#f.arguments[1].value.fields, 2)
  end)
  R.it("argument enum", function()
    local f = first_field("{ f(dir: ASC) }")
    R.eq(f.arguments[1].value.kind, 'EnumValue')
    return R.eq(f.arguments[1].value.value, 'ASC')
  end)
  R.it("argument variable", function()
    local f = first_field("{ f(x: $myVar) }")
    R.eq(f.arguments[1].value.kind, 'Variable')
    return R.eq(f.arguments[1].value.name, 'myVar')
  end)
  return R.it("plusieurs arguments", function()
    local f = first_field("{ f(a: 1, b: 2, c: 3) }")
    return R.eq(#f.arguments, 3)
  end)
end)
R.describe("Parser — variables de l'opération", function()
  R.it("une variable", function()
    local def = first_def("query($id: ID!) { f(x: $id) }")
    R.eq(#def.variableDefs, 1)
    local vd = def.variableDefs[1]
    R.eq(vd.name, 'id')
    R.eq(vd.type.kind, 'NonNullType')
    return R.eq(vd.type.ofType.name, 'ID')
  end)
  R.it("plusieurs variables", function()
    local def = first_def("query($a: Int, $b: String) { f }")
    return R.eq(#def.variableDefs, 2)
  end)
  return R.it("variable avec valeur par défaut", function()
    local def = first_def("query($n: Int = 0) { f }")
    local vd = def.variableDefs[1]
    return R.eq(vd.defaultValue.value, '0')
  end)
end)
R.describe("Parser — références de types", function()
  R.it("type nommé", function()
    local def = first_def("type T { f: String }")
    local field_type = def.fields[1].type
    R.eq(field_type.kind, 'NamedType')
    return R.eq(field_type.name, 'String')
  end)
  R.it("type non-nul", function()
    local def = first_def("type T { f: String! }")
    R.eq(def.fields[1].type.kind, 'NonNullType')
    return R.eq(def.fields[1].type.ofType.name, 'String')
  end)
  R.it("type liste", function()
    local def = first_def("type T { f: [String] }")
    R.eq(def.fields[1].type.kind, 'ListType')
    return R.eq(def.fields[1].type.ofType.name, 'String')
  end)
  return R.it("type liste non-nul", function()
    local def = first_def("type T { f: [String!]! }")
    local outer = def.fields[1].type
    R.eq(outer.kind, 'NonNullType')
    local inner = outer.ofType
    R.eq(inner.kind, 'ListType')
    return R.eq(inner.ofType.kind, 'NonNullType')
  end)
end)
R.describe("Parser — fragments", function()
  R.it("définition de fragment", function()
    local doc = parse("fragment Fields on User { name email }")
    local def = doc.definitions[1]
    R.eq(def.kind, 'FragmentDefinition')
    R.eq(def.name, 'Fields')
    R.eq(def.typeCondition, 'User')
    return R.eq(#def.selectionSet.selections, 2)
  end)
  R.it("spread de fragment", function()
    local f = first_field("{ ...MyFrag }")
    R.eq(f.kind, 'FragmentSpread')
    return R.eq(f.name, 'MyFrag')
  end)
  R.it("fragment inline", function()
    local f = first_field("{ ... on User { name } }")
    R.eq(f.kind, 'InlineFragment')
    return R.eq(f.typeCondition, 'User')
  end)
  return R.it("fragment inline sans type", function()
    local f = first_field("{ ... { name } }")
    R.eq(f.kind, 'InlineFragment')
    return R.is_nil(f.typeCondition)
  end)
end)
R.describe("Parser — SDL : types objet", function()
  R.it("type objet simple", function()
    local def = first_def("type User { name: String! }")
    R.eq(def.kind, 'ObjectTypeDefinition')
    R.eq(def.name, 'User')
    R.eq(#def.fields, 1)
    return R.eq(def.fields[1].name, 'name')
  end)
  R.it("plusieurs champs", function()
    local def = first_def("type User { id: ID! name: String email: String }")
    return R.eq(#def.fields, 3)
  end)
  R.it("description de type", function()
    local def = first_def('"""Mon type""" type Foo { x: Int }')
    R.ok(def.description)
    return R.matches(def.description, 'Mon type')
  end)
  return R.it("champ avec argument SDL", function()
    local def = first_def("type Q { f(limit: Int = 10): [String] }")
    local arg = def.fields[1].arguments[1]
    R.eq(arg.name, 'limit')
    return R.eq(arg.defaultValue.value, '10')
  end)
end)
R.describe("Parser — SDL : scalaires, enums, unions, inputs", function()
  R.it("scalaire", function()
    local def = first_def("scalar Date")
    R.eq(def.kind, 'ScalarTypeDefinition')
    return R.eq(def.name, 'Date')
  end)
  R.it("enum", function()
    local def = first_def("enum Color { RED GREEN BLUE }")
    R.eq(def.kind, 'EnumTypeDefinition')
    R.eq(#def.values, 3)
    return R.eq(def.values[1].name, 'RED')
  end)
  R.it("union", function()
    local def = first_def("union Result = Foo | Bar")
    R.eq(def.kind, 'UnionTypeDefinition')
    return R.eq(#def.types, 2)
  end)
  R.it("input object", function()
    local def = first_def("input CreateUser { name: String! email: String }")
    R.eq(def.kind, 'InputObjectTypeDefinition')
    return R.eq(#def.fields, 2)
  end)
  return R.it("interface", function()
    local def = first_def("interface Node { id: ID! }")
    return R.eq(def.kind, 'InterfaceTypeDefinition')
  end)
end)
return R.describe("Parser — erreurs", function()
  R.it("accolade fermante manquante", function()
    return R.raises((function()
      return parse("{ hello ")
    end), nil, 'erreur syntaxique attendue')
  end)
  return R.it("source vide → document vide", function()
    local doc = parse("")
    R.eq(doc.kind, 'Document')
    return R.eq(#doc.definitions, 0)
  end)
end)
