// Generated by CoffeeScript 2.7.0
(function() {
  // auth.coffee
  // Handles login, logout, current-user state, and password management.
  var ADD_MEMBER_MUTATION, CHANGE_PASSWORD_MUTATION, CREATE_GROUP_MUTATION, CREATE_USER_MUTATION, DELETE_GROUP_MUTATION, GRANT_MUTATION, LIST_GROUPS_QUERY, LIST_USERS_QUERY, LOGIN_MUTATION, LOGOUT_MUTATION, ME_QUERY, REMOVE_MEMBER_MUTATION, REVOKE_MUTATION;

  LOGIN_MUTATION = `mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    token
    user { id username email groups { id name } }
  }
}`;

  LOGOUT_MUTATION = `mutation { logout }`;

  ME_QUERY = `query { me { id username email groups { id name } } }`;

  CHANGE_PASSWORD_MUTATION = `mutation ChangePassword($currentPassword: String!, $newPassword: String!) {
  changePassword(currentPassword: $currentPassword, newPassword: $newPassword)
}`;

  CREATE_USER_MUTATION = `mutation CreateUser($input: CreateUserInput!) {
  createUser(input: $input) { id username email }
}`;

  LIST_USERS_QUERY = `query { users { id username email groups { id name } } }`;

  LIST_GROUPS_QUERY = `query { groups { id name description members { id username } permissions { id resourceType resourceId level } } }`;

  CREATE_GROUP_MUTATION = `mutation CreateGroup($input: CreateGroupInput!) {
  createGroup(input: $input) { id name description }
}`;

  DELETE_GROUP_MUTATION = `mutation DeleteGroup($id: ID!) { deleteGroup(id: $id) }`;

  ADD_MEMBER_MUTATION = `mutation AddMember($userId: ID!, $groupId: ID!) { addMember(userId: $userId, groupId: $groupId) }`;

  REMOVE_MEMBER_MUTATION = `mutation RemoveMember($userId: ID!, $groupId: ID!) { removeMember(userId: $userId, groupId: $groupId) }`;

  GRANT_MUTATION = `mutation Grant($groupId: ID!, $input: PermissionInput!) {
  grant(groupId: $groupId, input: $input) { id resourceType resourceId level }
}`;

  REVOKE_MUTATION = `mutation Revoke($permissionId: ID!) { revoke(permissionId: $permissionId) }`;

  window.Auth = {
    currentUser: null,
    isAdmin: function() {
      var ref;
      if (!((ref = this.currentUser) != null ? ref.groups : void 0)) {
        return false;
      }
      return this.currentUser.groups.some(function(g) {
        return g.name === 'admin';
      });
    },
    login: function(username, password) {
      return GQL.mutate(LOGIN_MUTATION, {username, password}).then(function(data) {
        GQL.setToken(data.login.token);
        Auth.currentUser = data.login.user;
        return Auth.currentUser;
      });
    },
    logout: function() {
      return GQL.mutate(LOGOUT_MUTATION).finally(function() {
        GQL.clearToken();
        Auth.currentUser = null;
        return App.showLogin();
      });
    },
    restoreSession: function() {
      return GQL.query(ME_QUERY).then(function(data) {
        if (data.me) {
          Auth.currentUser = data.me;
          return Auth.currentUser;
        } else {
          return null;
        }
      }).catch(function() {
        return null;
      });
    },
    changePassword: function(currentPassword, newPassword) {
      return GQL.mutate(CHANGE_PASSWORD_MUTATION, {currentPassword, newPassword}).then(function(data) {
        return data.changePassword;
      });
    },
    // Admin-only operations
    createUser: function(username, email, password) {
      return GQL.mutate(CREATE_USER_MUTATION, {
        input: {username, email, password}
      }).then(function(data) {
        return data.createUser;
      });
    },
    listUsers: function() {
      return GQL.query(LIST_USERS_QUERY).then(function(data) {
        return data.users;
      });
    },
    listGroups: function() {
      return GQL.query(LIST_GROUPS_QUERY).then(function(data) {
        return data.groups;
      });
    },
    createGroup: function(name, description = '') {
      return GQL.mutate(CREATE_GROUP_MUTATION, {
        input: {name, description}
      }).then(function(data) {
        return data.createGroup;
      });
    },
    deleteGroup: function(id) {
      return GQL.mutate(DELETE_GROUP_MUTATION, {id});
    },
    addMember: function(userId, groupId) {
      return GQL.mutate(ADD_MEMBER_MUTATION, {userId, groupId});
    },
    removeMember: function(userId, groupId) {
      return GQL.mutate(REMOVE_MEMBER_MUTATION, {userId, groupId});
    },
    grant: function(groupId, resourceType, resourceId, level) {
      return GQL.mutate(GRANT_MUTATION, {
        groupId,
        input: {resourceType, resourceId, level}
      }).then(function(data) {
        return data.grant;
      });
    },
    revoke: function(permissionId) {
      return GQL.mutate(REVOKE_MUTATION, {permissionId});
    }
  };

}).call(this);
