// Generated by CoffeeScript 2.7.0
(function() {
  // data_view.coffee
  // Raw data grid view using Toast UI Grid (tui.Grid).
  var DELETE_RECORD, DataView, INSERT_RECORD, RECORDS_QUERY, UPDATE_RECORD, gqlName,
    hasProp = {}.hasOwnProperty;

  RECORDS_QUERY = `query Records($spaceId: ID!, $limit: Int, $offset: Int, $filter: RecordFilter) {
  records(spaceId: $spaceId, limit: $limit, offset: $offset, filter: $filter) {
    items { id data }
    total
  }
}`;

  // Convert a space name to a valid GraphQL identifier (mirrors backend gql_name).
  gqlName = function(name) {
    var s;
    s = name.replace(/[^\w]/g, '_');
    if (/^\d/.test(s)) {
      return '_' + s;
    } else {
      return s;
    }
  };

  INSERT_RECORD = `mutation InsertRecord($spaceId: ID!, $data: JSON!) {
  insertRecord(spaceId: $spaceId, data: $data) { id data }
}`;

  UPDATE_RECORD = `mutation UpdateRecord($spaceId: ID!, $id: ID!, $data: JSON!) {
  updateRecord(spaceId: $spaceId, id: $id, data: $data) { id data }
}`;

  DELETE_RECORD = `mutation DeleteRecord($spaceId: ID!, $id: ID!) {
  deleteRecord(spaceId: $spaceId, id: $id)
}`;

  window.DataView = DataView = class DataView {
    constructor(container, space, filter1 = null, relations = []) {
      this.container = container;
      this.space = space;
      this.filter = filter1;
      this._grid = null; // tui.Grid instance
      this._rows = []; // rows from server
      this._currentData = []; // rows currently displayed (filtered + sentinel)
      this._defaultValues = {}; // FK defaults for new records (set by depends_on)
      this._mounted = false; // true after mount() completes, false after unmount()
      this._relations = relations;
      this._fkMaps = {}; // field name → { id → display label }
      this._fkOptions = {}; // field name → [{ text, value }]
      this._formulaFilter = ''; // Lua/MoonScript formula for server-side row filtering
      this._formulaTimer = null; // debounce handle
    }

    
      // Build FK display maps for all relation fields.
    async _buildFkMaps() {
      var data, display, e, field, fkId, formula, j, jsFormula, l, len, len1, map, options, rec, records, ref, ref1, ref2, ref3, ref4, rel, reprFn, results;
      ref = this._relations;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        rel = ref[j];
        field = (this.space.fields || []).find(function(f) {
          return f.id === rel.fromFieldId;
        });
        if (!field) {
          continue;
        }
        try {
          data = (await GQL.query(RECORDS_QUERY, {
            spaceId: rel.toSpaceId,
            limit: 5000
          }));
          records = data.records.items.map(function(r) {
            var parsed;
            parsed = typeof r.data === 'string' ? JSON.parse(r.data) : r.data;
            return Object.assign({
              __rowId: r.id
            }, parsed);
          });
          reprFn = null;
          formula = (ref1 = rel.reprFormula) != null ? ref1.trim() : void 0;
          if (formula) {
            // Transpile MoonScript repr formula → JavaScript
            jsFormula = formula.replace(/\.\./g, '+').replace(/ and /g, ' && ').replace(/ or /g, ' || ').replace(/\bnil\b/g, 'null'); // string concat // boolean and // boolean or // nil → null
            try {
              reprFn = new Function('self', `try { return String(${jsFormula}); } catch(e) { return String(self.id || ''); }`);
            } catch (error) {
              reprFn = null;
            }
          }
          map = {};
          options = [];
          for (l = 0, len1 = records.length; l < len1; l++) {
            rec = records[l];
            display = reprFn ? reprFn(rec) : rec._repr != null ? String(rec._repr) : String((ref2 = (ref3 = rec.id) != null ? ref3 : rec[Object.keys(rec)[0]]) != null ? ref2 : '');
            // FK columns store the integer sequence value (rec.id), not the Tarantool UUID
            fkId = (ref4 = rec.id) != null ? ref4 : rec[Object.keys(rec).find(function(k) {
              return k !== '__rowId';
            })];
            map[String(fkId)] = display;
            options.push({
              text: display,
              value: String(fkId)
            });
          }
          options.sort(function(a, b) {
            return a.text.localeCompare(b.text);
          });
          this._fkMaps[field.name] = map;
          results.push(this._fkOptions[field.name] = options);
        } catch (error) {
          e = error;
          results.push(console.warn(`FK map build failed for ${field.name}:`, e));
        }
      }
      return results;
    }

    async mount() {
      var col, columns, editableCols, f, fields, fkMap, fkOptions, formulaNames, ref, saved, seqNames, wrapper;
      this._mounted = true;
      this.container.innerHTML = '';
      wrapper = document.createElement('div');
      wrapper.style.cssText = 'width:100%;height:100%;';
      this.container.appendChild(wrapper);
      fields = this.space.fields || [];
      seqNames = new Set((function() {
        var j, len, results;
        results = [];
        for (j = 0, len = fields.length; j < len; j++) {
          f = fields[j];
          if (f.fieldType === 'Sequence') {
            results.push(f.name);
          }
        }
        return results;
      })());
      formulaNames = new Set((function() {
        var j, len, results;
        results = [];
        for (j = 0, len = fields.length; j < len; j++) {
          f = fields[j];
          if (f.formula && f.formula !== '' && !f.triggerFields) {
            results.push(f.name);
          }
        }
        return results;
      })());
      saved = this._loadColWidths();
      if (((ref = this._relations) != null ? ref.length : void 0) > 0) {
        await this._buildFkMaps();
      }
      columns = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = fields.length; j < len; j++) {
          f = fields[j];
          col = {
            name: f.name,
            header: f.name,
            width: saved[f.name] || 160,
            minWidth: 40,
            resizable: true,
            sortable: true
          };
          if (this._fkMaps[f.name] != null) {
            fkMap = this._fkMaps[f.name];
            fkOptions = this._fkOptions[f.name] || [];
            col.formatter = (function(fkMap) {
              return function(props) {
                var ref1, val;
                val = props.value;
                return (ref1 = fkMap[String(val)]) != null ? ref1 : String(val != null ? val : '');
              };
            })(fkMap);
            col.editor = {
              type: 'select',
              options: {
                listItems: fkOptions
              }
            };
          } else {
            if (!(seqNames.has(f.name) || formulaNames.has(f.name))) {
              col.editor = 'text';
            }
          }
          results.push(col);
        }
        return results;
      }).call(this);
      this._grid = new tui.Grid({
        el: wrapper,
        columns: columns,
        data: [],
        bodyHeight: 'fitToParent',
        rowHeight: 28,
        minRowHeight: 28,
        header: {
          height: 28
        },
        rowHeaders: ['checkbox'],
        scrollX: true,
        scrollY: true,
        copyOptions: {
          useFormattedValue: true
        }
      });
      // Detect Ctrl+V to distinguish paste from manual edit on the sentinel
      this._pasting = false;
      this._pasteListener = (e) => {
        if (e.key === 'v' && (e.ctrlKey || e.metaKey)) {
          this._pasting = true;
          return setTimeout((() => {
            return this._pasting = false;
          }), 300);
        }
      };
      document.addEventListener('keydown', this._pasteListener);
      // Persist column widths on resize
      this._grid.on('columnResized', ({columnName, width}) => {
        var saved2;
        saved2 = this._loadColWidths();
        saved2[columnName] = width;
        return localStorage.setItem(this._lsKey(), JSON.stringify(saved2));
      });
      // Tab / Shift+Tab: move to next/prev editable cell on the same row,
      // wrapping to the next/prev row at row boundaries.
      // Use capture phase to intercept before tui.Grid's own Tab handler.
      editableCols = columns.filter(function(c) {
        return c.editor;
      }).map(function(c) {
        return c.name;
      });
      wrapper.addEventListener('keydown', (e) => {
        var cell, idx, nextRow, prevRow, rowCount, rowIdx;
        if (e.key !== 'Tab') {
          return;
        }
        cell = this._grid.getFocusedCell();
        if (!(cell != null ? cell.columnName : void 0)) {
          return;
        }
        idx = editableCols.indexOf(cell.columnName);
        if (idx < 0) {
          return;
        }
        e.preventDefault();
        e.stopImmediatePropagation();
        rowIdx = this._grid.getIndexOfRow(cell.rowKey);
        rowCount = this._grid.getRowCount();
        if (e.shiftKey) {
          if (idx > 0) {
            // Previous column, same row
            return setTimeout(() => {
              this._grid.focus(cell.rowKey, editableCols[idx - 1]);
              return this._grid.startEditing(cell.rowKey, editableCols[idx - 1]);
            }, 0);
          } else if (rowIdx > 0) {
            // Last column of previous row (skip sentinel at end)
            prevRow = this._grid.getRowAt(rowIdx - 1);
            if (!(prevRow != null ? prevRow.__isNew : void 0)) {
              return setTimeout(() => {
                this._grid.focus(prevRow.rowKey, editableCols[editableCols.length - 1]);
                return this._grid.startEditing(prevRow.rowKey, editableCols[editableCols.length - 1]);
              }, 0);
            }
          }
        } else {
          if (idx < editableCols.length - 1) {
            // Next column, same row
            return setTimeout(() => {
              this._grid.focus(cell.rowKey, editableCols[idx + 1]);
              return this._grid.startEditing(cell.rowKey, editableCols[idx + 1]);
            }, 0);
          } else {
            // First column of next row (skip sentinel)
            nextRow = this._grid.getRowAt(rowIdx + 1);
            if ((nextRow != null) && !nextRow.__isNew) {
              return setTimeout(() => {
                this._grid.focus(nextRow.rowKey, editableCols[0]);
                return this._grid.startEditing(nextRow.rowKey, editableCols[0]);
              }, 0);
            }
          }
        }
      }, true); // capture: true
      
      // Handle cell edits (single edit and paste)
      this._grid.on('afterChange', async(ev) => {
        var byRow, c, changes, clipErr, clipRow, clipRows, clipText, colNames, data, i, j, l, len, len1, len2, len3, len4, m, n, name, name1, o, ops, p, patch, ref1, ref2, ref3, ref4, ref5, ref6, rk, row, sentinelPatch, val;
        changes = (ev.changes || []).filter(function(c) {
          return String(c.value) !== String(c.prevValue);
        });
        if (!changes.length) {
          return;
        }
        // Group field changes by row
        byRow = {};
        for (j = 0, len = changes.length; j < len; j++) {
          c = changes[j];
          if (byRow[name1 = c.rowKey] == null) {
            byRow[name1] = {};
          }
          byRow[c.rowKey][c.columnName] = c.value;
        }
        colNames = (function() {
          var l, len1, results;
          results = [];
          for (l = 0, len1 = fields.length; l < len1; l++) {
            f = fields[l];
            if (!seqNames.has(f.name) && !formulaNames.has(f.name)) {
              results.push(f.name);
            }
          }
          return results;
        })();
        ops = [];
        sentinelPatch = null;
        for (rk in byRow) {
          if (!hasProp.call(byRow, rk)) continue;
          patch = byRow[rk];
          for (name in patch) {
            if (!hasProp.call(patch, name)) continue;
            val = patch[name];
            if ((this._fkMaps[name] != null) && (val != null) && val !== '') {
              patch[name] = Number(val);
            }
          }
          // Resolve actual row data from tui.Grid (rowKey ≠ array index after resetData)
          row = this._grid.getRow(Number(rk));
          if (row != null ? row.__isNew : void 0) {
            sentinelPatch = patch;
          } else if (row != null ? row.__rowId : void 0) {
            ops.push(GQL.mutate(UPDATE_RECORD, {
              spaceId: this.space.id,
              id: row.__rowId,
              data: JSON.stringify(patch)
            }));
          }
        }
        // Insertion(s) from sentinel
        if (sentinelPatch) {
          if (this._pasting) {
            try {
              // Re-read clipboard to get all pasted rows (TUI only fills the one sentinel row)
              clipText = (await navigator.clipboard.readText());
              clipRows = clipText.replace(/\r\n/g, '\n').replace(/\r/g, '\n').split('\n').map(function(line) {
                return line.split('\t');
              }).filter(function(cols) {
                return cols.some(function(c) {
                  return c.trim();
                });
              });
              for (l = 0, len1 = clipRows.length; l < len1; l++) {
                clipRow = clipRows[l];
                data = {};
                for (i = m = 0, len2 = colNames.length; m < len2; i = ++m) {
                  name = colNames[i];
                  data[name] = (ref1 = (ref2 = clipRow[i]) != null ? ref2 : this._defaultValues[name]) != null ? ref1 : '';
                }
                ops.push(GQL.mutate(INSERT_RECORD, {
                  spaceId: this.space.id,
                  data: JSON.stringify(data)
                }));
              }
            } catch (error) {
              clipErr = error;
              console.warn('clipboard unavailable, single insert fallback', clipErr);
              data = {};
              for (o = 0, len3 = colNames.length; o < len3; o++) {
                n = colNames[o];
                data[n] = (ref3 = (ref4 = sentinelPatch[n]) != null ? ref4 : this._defaultValues[n]) != null ? ref3 : '';
              }
              ops.push(GQL.mutate(INSERT_RECORD, {
                spaceId: this.space.id,
                data: JSON.stringify(data)
              }));
            }
          } else {
            // Manual edit: insert from sentinel values + defaults
            data = {};
            for (p = 0, len4 = colNames.length; p < len4; p++) {
              n = colNames[p];
              data[n] = (ref5 = (ref6 = sentinelPatch[n]) != null ? ref6 : this._defaultValues[n]) != null ? ref5 : '';
            }
            ops.push(GQL.mutate(INSERT_RECORD, {
              spaceId: this.space.id,
              data: JSON.stringify(data)
            }));
          }
        }
        return Promise.all(ops).then(() => {
          return this.load();
        }).catch((err) => {
          return this._showError(`Erreur d'enregistrement : ${err.message}`);
        });
      });
      return (await this.load());
    }

    // ── Data loading ─────────────────────────────────────────────────────────────
    _sentinel() {
      var f, j, len, ref, ref1, row;
      row = {
        __isNew: true
      };
      ref = this.space.fields || [];
      for (j = 0, len = ref.length; j < len; j++) {
        f = ref[j];
        if (f.fieldType !== 'Sequence') {
          row[f.name] = (ref1 = this._defaultValues[f.name]) != null ? ref1 : '';
        }
      }
      return row;
    }

    async load() {
      var data, f, fieldList, fields, formulaNames, gqlFilter, spaceQuery, tname;
      if (!this._mounted) {
        return;
      }
      fields = this.space.fields || [];
      formulaNames = new Set((function() {
        var j, len, results;
        results = [];
        for (j = 0, len = fields.length; j < len; j++) {
          f = fields[j];
          if (f.formula && f.formula !== '' && !f.triggerFields) {
            results.push(f.name);
          }
        }
        return results;
      })());
      if (formulaNames.size > 0 && !this._formulaFilter) {
        // Use the space-specific dynamic resolver so formula fields are evaluated.
        tname = gqlName(this.space.name);
        fieldList = ((function() {
          var j, len, results;
          results = [];
          for (j = 0, len = fields.length; j < len; j++) {
            f = fields[j];
            results.push(gqlName(f.name));
          }
          return results;
        })()).join(' ');
        spaceQuery = `query { ${tname}(limit: 2000) { items { _id ${fieldList} } } }`;
        data = (await GQL.query(spaceQuery, {}));
        if (!this._mounted) {
          return;
        }
        this._rows = data[tname].items.map(function(item) {
          var row;
          row = Object.assign({}, item);
          row.__rowId = item._id;
          return row;
        });
      } else {
        gqlFilter = this._formulaFilter ? {
          formula: this._formulaFilter,
          language: 'moonscript'
        } : void 0;
        data = (await GQL.query(RECORDS_QUERY, {
          spaceId: this.space.id,
          limit: 2000,
          filter: gqlFilter
        }));
        if (!this._mounted) {
          return;
        }
        this._rows = data.records.items.map(function(r) {
          var parsed, row;
          parsed = typeof r.data === 'string' ? JSON.parse(r.data) : r.data;
          row = Object.assign({}, parsed);
          row.__rowId = r.id;
          return row;
        });
      }
      this._applyData();
      return this._rows;
    }

    _applyData() {
      var lastIdx, rows, sentinelRow;
      if (!this._grid) {
        return;
      }
      rows = this._rows;
      if (this.filter) {
        rows = rows.filter((r) => {
          return String(r[this.filter.field]) === String(this.filter.value);
        });
      }
      this._currentData = rows.concat([this._sentinel()]);
      this._grid.resetData(this._currentData);
      // Find the actual rowKey tui.Grid assigned to the sentinel (last visual row)
      lastIdx = this._currentData.length - 1;
      sentinelRow = this._grid.getRowAt(lastIdx);
      if (sentinelRow != null) {
        return this._grid.addRowClassName(sentinelRow.rowKey, 'tdb-new-row');
      }
    }

    // ── Record actions ────────────────────────────────────────────────────────────
    insertBlank() {
      var data, f, fields, formulaNames, j, len, seqNames;
      fields = this.space.fields || [];
      seqNames = new Set((function() {
        var j, len, results;
        results = [];
        for (j = 0, len = fields.length; j < len; j++) {
          f = fields[j];
          if (f.fieldType === 'Sequence') {
            results.push(f.name);
          }
        }
        return results;
      })());
      formulaNames = new Set((function() {
        var j, len, results;
        results = [];
        for (j = 0, len = fields.length; j < len; j++) {
          f = fields[j];
          if (f.formula && f.formula !== '' && !f.triggerFields) {
            results.push(f.name);
          }
        }
        return results;
      })());
      data = {};
      for (j = 0, len = fields.length; j < len; j++) {
        f = fields[j];
        if (!seqNames.has(f.name) && !formulaNames.has(f.name)) {
          data[f.name] = '';
        }
      }
      return GQL.mutate(INSERT_RECORD, {
        spaceId: this.space.id,
        data: JSON.stringify(data)
      }).then(() => {
        return this.load();
      }).catch((err) => {
        return this._showError(`Erreur insertion : ${err.message}`);
      });
    }

    deleteSelected() {
      var keys, ops, toDelete;
      keys = this._grid.getCheckedRowKeys();
      if (!keys.length) {
        return;
      }
      // Filter out sentinel row
      toDelete = keys.map((rk) => {
        return this._currentData[Number(rk)];
      }).filter(function(row) {
        return row && !row.__isNew && row.__rowId;
      });
      if (!toDelete.length) {
        return;
      }
      ops = toDelete.map((row) => {
        return GQL.mutate(DELETE_RECORD, {
          spaceId: this.space.id,
          id: row.__rowId
        });
      });
      return Promise.all(ops).then(() => {
        return this.load();
      }).catch((err) => {
        return this._showError(`Erreur suppression : ${err.message}`);
      });
    }

    setDefaultValues(values) {
      return this._defaultValues = values || {};
    }

    setFilter(filter) {
      this.filter = filter;
      return this._applyData();
    }

    setFormulaFilter(formula) {
      this._formulaFilter = formula || '';
      return this.load();
    }

    // ── Error display ─────────────────────────────────────────────────────────────
    _showError(msg) {
      var close;
      if (!this._errorBanner) {
        this._errorBanner = document.createElement('div');
        this._errorBanner.className = 'data-view-error-banner';
        close = document.createElement('button');
        close.textContent = '✕';
        close.onclick = () => {
          return this._clearError();
        };
        this._errorBanner.appendChild(close);
        this._errorText = document.createElement('span');
        this._errorBanner.appendChild(this._errorText);
        this.container.insertBefore(this._errorBanner, this.container.firstChild);
      }
      this._errorText.textContent = msg;
      this._errorBanner.classList.remove('hidden');
      clearTimeout(this._errorTimer);
      return this._errorTimer = setTimeout((() => {
        return this._clearError();
      }), 6000);
    }

    _clearError() {
      var ref;
      return (ref = this._errorBanner) != null ? ref.classList.add('hidden') : void 0;
    }

    // ── Column width persistence ──────────────────────────────────────────────────
    _lsKey() {
      return `tdb_colwidths_${this.space.id}`;
    }

    _loadColWidths() {
      try {
        return JSON.parse(localStorage.getItem(this._lsKey()) || '{}');
      } catch (error) {
        return {};
      }
    }

    // ── Cleanup ───────────────────────────────────────────────────────────────────
    unmount() {
      var ref;
      this._mounted = false;
      clearTimeout(this._formulaTimer);
      if (this._pasteListener) {
        document.removeEventListener('keydown', this._pasteListener);
      }
      if ((ref = this._grid) != null) {
        ref.destroy();
      }
      this._grid = null;
      this._currentData = [];
      this._rows = [];
      return this.container.innerHTML = '';
    }

  };

}).call(this);
